sudo: false
language: rust
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build -- --all-features &&
  travis-cargo test -- --all-features
notifications:
  email:
    on_success: never
