[package]
name = "shared-bus"
version = "0.1.4"
authors = ["Rahix <rahix@rahix.de>"]
edition = "2018"

description = "Abstraction for sharing a bus between multiple devices."
homepage = "https://github.com/Rahix/shared-bus"
repository = "https://github.com/Rahix/shared-bus"
documentation = "https://docs.rs/shared-bus"
readme = "README.md"
keywords = ["embedded-hal", "embedded-hal-impl", "i2c", "spi", "bus"]
categories = ["embedded", "no-std"]
license = "MIT/Apache-2.0"

[package.metadata.docs.rs]
all-features = true

[dependencies]
embedded-hal = "0.2.3"
once_cell = { version = "1.4.0", optional = true }

[dependencies.cortex-m]
optional = true
version = "0.6.0"

[dev-dependencies]
embedded-hal-mock = "0.7.0"

[features]
std = ["once_cell"]
docsrs = []
cortexm = ["cortex-m"]
